spring:
  datasource:
    url: jdbc:mysql://47.107.41.60:3306/wisdomagriculture
    username: root
    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 9000
